apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world-cron
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo Hello world
              resources:
                limits:
                  cpu: "100m"
                  memory: 128Mi
                requests:
                  cpu: "50m"
                  memory: 64Mi
          restartPolicy: OnFailure
