apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    name: '${NAMESPACE}'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${NAMESPACE}-quota
  namespace: ${NAMESPACE}
spec:
  hard:
    requests.cpu: '${USERSPACE_CPU_REQUESTS}'
    requests.memory: '${USERSPACE_MEMORY_REQUESTS}'
    limits.cpu: '${USERSPACE_CPU_LIMITS}'
    limits.memory: '${USERSPACE_MEMORY_LIMITS}'
